apiVersion: v1
kind: Service
metadata:
  name: iscp-relay
spec:
  type: {{ .Values.relay.service.type }}
  selector:
    app: iscp-relay
  ports:
    - name: http
      port: {{ .Values.relay.port }}
      targetPort: http
