apiVersion: v1
kind: Service
metadata:
  name: iscp-trust-root
spec:
  type: {{ .Values.trustRoot.service.type }}
  selector:
    app: iscp-trust-root
  ports:
    - name: http
      port: {{ .Values.trustRoot.port }}
      targetPort: http
