apiVersion: apps/v1
kind: Deployment
metadata:
  name: iscp-trust-root
spec:
  replicas: {{ .Values.trustRoot.replicas }}
  selector:
    matchLabels:
      app: iscp-trust-root
  template:
    metadata:
      labels:
        app: iscp-trust-root
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: trust-root
          image: {{ .Values.trustRoot.image }}
          ports:
            - containerPort: {{ .Values.trustRoot.port }}
          env:
            - name: ISCP_PROFILE
              value: {{ .Values.profile | quote }}
            - name: ISCP_DOMAIN_ID
              value: {{ .Values.domainID | quote }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.trustRoot.port }}
          livenessProbe:
            httpGet:
              path: /livez
              port: {{ .Values.trustRoot.port }}

